# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CellOnApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CellOnApp

  pod 'IQKeyboardManager'
  pod 'GoogleSignIn', '~> 4.4.0'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

end
